<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_module ychoantien</name>
   <tag></tag>
   <elementGuidId>6abcee47-4a95-49e1-8455-869b385cec44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;side-menu&quot;)/li[4]/a[1][count(. | //a[@href = '#' and (text() = ' Yêu cầu hoàn tiền' or . = ' Yêu cầu hoàn tiền')]) = count(//a[@href = '#' and (text() = ' Yêu cầu hoàn tiền' or . = ' Yêu cầu hoàn tiền')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;side-menu&quot;]/li[4]/a/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#side-menu > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54f5e121-b27a-4134-8d73-55dd44b3d145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2a395d58-a689-46b4-8227-d1791e5ff795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Yêu cầu hoàn tiền</value>
      <webElementGuid>befc1fe8-cc7d-4620-a1e8-9d5e21cbc957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-menu&quot;)/li[4]/a[1]</value>
      <webElementGuid>56a4e68f-51ee-4d63-afcc-3e488dbff55e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side-menu']/li[4]/a</value>
      <webElementGuid>6336a2ff-02d8-497c-925e-b3b23996d402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách thông báo giao dịch'])[1]/following::a[1]</value>
      <webElementGuid>2a302e65-5238-453e-baf2-1b56b04f8f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duyệt giao dịch chi hộ rủi ro'])[1]/following::a[2]</value>
      <webElementGuid>8440557a-16ac-4ee7-8746-3b348849ddb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách yêu cầu'])[1]/preceding::a[1]</value>
      <webElementGuid>136119dc-3f2f-42e7-b133-75038e3e2944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>4ba563ce-339d-4a86-8820-58acf2c6846f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>734445e5-c503-4898-8442-4bf24f8682ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Yêu cầu hoàn tiền' or . = ' Yêu cầu hoàn tiền')]</value>
      <webElementGuid>dbfb6800-2f0a-4f5e-ba4c-68f85a1def3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
