<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The Transaction can be partially refunded after 24 hours of success</name>
   <tag></tag>
   <elementGuidId>5e86d5fa-e79d-428e-8091-48fdf04953aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div[2]/div/div/div/form/div[4]/div[2]/div/span/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.f-13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;The Transaction can be partially refunded after 24 hours of success.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>55889f40-0443-4368-848f-fb0d6640a55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f-13</value>
      <webElementGuid>9cb5d531-4579-4ff9-abd7-2b75a2ddf57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Transaction can be partially refunded after 24 hours of success.</value>
      <webElementGuid>fd52dda0-a66c-4f2e-8c6f-91a32e86a909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;ant-card ant-card ant-card-bordered&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;pr-10 pl-10 ant-col ant-col-xs-24 ant-col-xl-12&quot;]/form[@class=&quot;ant-form ant-form-vertical&quot;]/div[@class=&quot;ant-row ant-form-item&quot;]/div[@class=&quot;ant-col ant-col-18 ant-form-item-control-wrapper&quot;]/div[@class=&quot;ant-form-item-control has-success&quot;]/span[@class=&quot;ant-form-item-children&quot;]/p[@class=&quot;f-13&quot;]</value>
      <webElementGuid>b4e2ec82-11e3-44d0-8cac-736127c6a2cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/div/form/div[4]/div[2]/div/span/p</value>
      <webElementGuid>5a79b94d-cc79-4648-98e7-f7483b0ce256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partial refund'])[1]/following::p[1]</value>
      <webElementGuid>c6538695-55c7-4882-923f-84de93d044c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full refund'])[1]/following::p[1]</value>
      <webElementGuid>5b0f2dd9-0a4a-4063-8ee3-27154c414eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::p[1]</value>
      <webElementGuid>3cfda30d-ecad-4d01-9c9c-e1aac59d10c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Transaction can be partially refunded after 24 hours of success.']/parent::*</value>
      <webElementGuid>f5c5d0d7-4b11-44f2-a714-657f5d53c38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>beb11692-f423-4abc-9f13-4919c1f51faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The Transaction can be partially refunded after 24 hours of success.' or . = 'The Transaction can be partially refunded after 24 hours of success.')]</value>
      <webElementGuid>a59d4219-f264-4981-954b-7b492939940e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
