<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_T chi</name>
   <tag></tag>
   <elementGuidId>1f0b47dd-e038-45b3-8fd1-bcadc68ce769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[3]/div/div/div[1]/div/div[3]/div[1]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reject-btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;reject-btn&quot;)[count(. | //*[@type = 'button' and @class = 'btn btn-danger ladda-button mr-3' and @id = 'reject-btn' and (text() = 'Từ chối yêu cầu' or . = 'Từ chối yêu cầu')]) = count(//*[@type = 'button' and @class = 'btn btn-danger ladda-button mr-3' and @id = 'reject-btn' and (text() = 'Từ chối yêu cầu' or . = 'Từ chối yêu cầu')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68023b85-88e2-4e59-88b8-ae14ea406a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d990f50-9d75-4db6-a902-f1e44196a0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger ladda-button mr-3</value>
      <webElementGuid>e1c56fdf-4e09-44d3-9558-c123df800715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reject-btn</value>
      <webElementGuid>d12fa4e9-30b8-472e-b534-3489bc1fd3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>expand-right</value>
      <webElementGuid>c7012c15-9d92-4ef8-8f11-74e9baa790f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Từ chối yêu cầu</value>
      <webElementGuid>04a1d583-bd8b-49e1-928c-f8c3516d0819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reject-btn&quot;)</value>
      <webElementGuid>6f0982eb-3008-435c-b327-6d1e23ed8fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reject-btn']</value>
      <webElementGuid>83433fe2-25d6-44c1-9e69-b1e111063c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[3]/div/div/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>0214e010-bbc2-40fb-9f20-f21aab65378b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiển thị từ 1 đến 20 của 31 bản ghi'])[1]/following::button[1]</value>
      <webElementGuid>532dbc73-813a-42fa-b2e8-5265ad716f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duyệt yêu cầu'])[1]/preceding::button[1]</value>
      <webElementGuid>520b7dfc-6514-4e85-9b7f-4dc8ce6ddc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>241dace1-f01a-4886-9861-a4930bb08a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'reject-btn' and (text() = 'Từ chối yêu cầu' or . = 'Từ chối yêu cầu')]</value>
      <webElementGuid>6adc6be1-01ad-41b6-ad04-df5a37570bc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
