<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Duyt</name>
   <tag></tag>
   <elementGuidId>8ebf37a6-99bc-40a3-95da-bfa0261ecb50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[3]/div/div/div[1]/div/div[3]/div[1]/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approve-btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;approve-btn&quot;)[count(. | //*[@type = 'button' and @class = 'btn btn-success ladda-button' and @id = 'approve-btn' and (text() = 'Duyệt yêu cầu' or . = 'Duyệt yêu cầu')]) = count(//*[@type = 'button' and @class = 'btn btn-success ladda-button' and @id = 'approve-btn' and (text() = 'Duyệt yêu cầu' or . = 'Duyệt yêu cầu')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77c7d21f-a4a7-4592-ab17-3f6fb172d911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4f9412a-f036-4c17-9b53-d4d2711c59d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success ladda-button</value>
      <webElementGuid>e307c83c-d41c-4f93-b43d-f081e0bb0845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approve-btn</value>
      <webElementGuid>873458b4-1939-4040-a37b-1d386d93c7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>expand-right</value>
      <webElementGuid>7670809a-53ce-43fe-8056-b9b3208c3855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Duyệt yêu cầu</value>
      <webElementGuid>e904c799-4595-4e68-8651-e39888c90113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approve-btn&quot;)</value>
      <webElementGuid>991a52c4-72f3-4535-b263-607e418967df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='approve-btn']</value>
      <webElementGuid>54b6c845-6ca4-4670-9ff7-ef94c577c3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[3]/div/div/div/div/div[3]/div/div[2]/button[2]</value>
      <webElementGuid>9922d9f4-4c4b-4bcc-9af5-f2384ca13557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Từ chối yêu cầu'])[1]/following::button[1]</value>
      <webElementGuid>1803a5e8-e0d9-4ed0-b4a6-b30454d90fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiển thị từ 1 đến 20 của 31 bản ghi'])[1]/following::button[2]</value>
      <webElementGuid>3a4626c2-9b79-4a65-a3db-207d3130393e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STT'])[1]/preceding::button[1]</value>
      <webElementGuid>c15bcf51-b88d-4d30-bdae-0a615e65f9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4a424df5-545c-4150-88d6-3f8564757409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'approve-btn' and (text() = 'Duyệt yêu cầu' or . = 'Duyệt yêu cầu')]</value>
      <webElementGuid>ea0a8e6a-0806-4861-a1c5-4403eb570bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
