<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_T chi</name>
   <tag></tag>
   <elementGuidId>1f0b47dd-e038-45b3-8fd1-bcadc68ce769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;reject-btn&quot;)[count(. | //*[@type = 'button' and @class = 'btn btn-danger ladda-button mr-3' and @id = 'reject-btn' and (text() = 'Từ chối yêu cầu' or . = 'Từ chối yêu cầu')]) = count(//*[@type = 'button' and @class = 'btn btn-danger ladda-button mr-3' and @id = 'reject-btn' and (text() = 'Từ chối yêu cầu' or . = 'Từ chối yêu cầu')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[3]/div/div/div[1]/div/div[3]/div[1]/div[2]/button[1]/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reject-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bd8f9a9-ac04-4917-b8ea-961227eea2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5575376e-29f8-493a-899c-13b55cd27ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger ladda-button mr-3</value>
      <webElementGuid>2564151c-6a80-49f0-865b-25247ac2ce44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reject-btn</value>
      <webElementGuid>dd1e4bc1-832b-4f98-aa11-758c58b6b81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>expand-right</value>
      <webElementGuid>ea2c0872-7bb9-4c07-bd30-a5b734c623b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Từ chối yêu cầu</value>
      <webElementGuid>2819f713-06e3-48b0-b43f-78ad1a09a4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reject-btn&quot;)</value>
      <webElementGuid>6dc6c995-1840-4c44-90f5-9d18137d73ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reject-btn']</value>
      <webElementGuid>ddfd23f5-f247-4a5b-a4eb-b984e7d176e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[3]/div/div/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>0cbe28d5-e11d-4a16-872b-25f378a1f9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiển thị từ 1 đến 20 của 31 bản ghi'])[1]/following::button[1]</value>
      <webElementGuid>c1cce76c-2bbb-4b87-95e9-6fab2b090a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duyệt yêu cầu'])[1]/preceding::button[1]</value>
      <webElementGuid>7b75f02a-1c4a-4694-aa6e-4d11c02a4b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>60925d9b-8a0e-4943-a3fb-529566fbe6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'reject-btn' and (text() = 'Từ chối yêu cầu' or . = 'Từ chối yêu cầu')]</value>
      <webElementGuid>6a0f4818-2521-486b-aca7-5ff28c870045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
