<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vcb</name>
   <tag></tag>
   <elementGuidId>302139b6-dcec-4521-a702-4e90ba2c4bdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/main/div[2]/div/div[1]/div[1]/form/div[9]/div[2]/div/span/div/div/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bank-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Ngân hàng TMCP Ngoại thương Việt Nam&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19c929e7-87ae-4e71-982d-7a982b3dac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bank-info</value>
      <webElementGuid>90afc573-a57e-460b-a4e7-48ee2a93b789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngân hàng TMCP Ngoại thương Việt Nam</value>
      <webElementGuid>8d006f40-9e7a-45c6-9dec-afe245f9771c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;001beeea-48ca-4c57-e02d-8483665c7c8e&quot;)/ul[@class=&quot;ant-select-dropdown-menu ant-select-dropdown-menu-vertical ant-select-dropdown-menu-root&quot;]/li[@class=&quot;ant-select-dropdown-menu-item ant-select-dropdown-menu-item-active&quot;]/div[@class=&quot;bank-info&quot;]</value>
      <webElementGuid>fb689451-ca13-4f1b-ae12-998b8bd973de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='001beeea-48ca-4c57-e02d-8483665c7c8e']/ul/li[2]/div</value>
      <webElementGuid>89f19d2f-4a3f-4167-b9fc-6c714b843054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn ngân hàng'])[1]/following::div[1]</value>
      <webElementGuid>54c6a0f2-55b8-47ae-ae49-168a1753151b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[5]</value>
      <webElementGuid>1c1319b1-db51-497d-bb9e-c8685883386d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngân hàng TMCP Đầu tư và Phát triển Việt Nam'])[1]/preceding::div[1]</value>
      <webElementGuid>8ee6fd80-6c85-4b55-89b4-1a755cc009c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div</value>
      <webElementGuid>0133d3f1-d319-4878-8734-35ea765c72e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ngân hàng TMCP Ngoại thương Việt Nam' or . = 'Ngân hàng TMCP Ngoại thương Việt Nam')]</value>
      <webElementGuid>64b1af69-5ea8-489a-ab2d-538fc6ce4426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
