<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>d15e3d40-4cb0-4f1c-9d22-50994cb23c8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5ecc304-ced3-4fc8-bc8b-b19ea24a45f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b5d04486-2618-47de-96d6-2a3f9ba6be6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__input form-control w-100</value>
      <webElementGuid>d226f491-7de3-40d8-972b-b2fdadc90231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cf09c1bd-9e74-4d9b-9460-9f6497773752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>invalid-message</name>
      <type>Main</type>
      <value>Mật khẩu không được để trống</value>
      <webElementGuid>08bcf1e2-8a2d-4d3e-be64-a60c66edb08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container vh-100&quot;]/div[@class=&quot;row justify-content-center d-flex align-items-center vh-100&quot;]/div[@class=&quot;col-md-8 py-4 box-content&quot;]/div[@class=&quot;card box-login shadow-lg&quot;]/div[@class=&quot;card-body p-5&quot;]/div[@class=&quot;form-login d-flex justify-content-center mb-5&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mb-3 w-100 position-relative box-input&quot;]/input[@class=&quot;form__input form-control w-100&quot;]</value>
      <webElementGuid>70523a13-f80d-45cf-a919-6e971d6d70d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>bf3eacd8-9c4b-4223-9bb2-473e6934e0ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4b16d599-7fce-4818-a32c-920e560ab19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password']</value>
      <webElementGuid>2c6e14e4-61da-4803-9d81-86c70b05805b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
