<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Refund</name>
   <tag></tag>
   <elementGuidId>af49ef15-5c93-4e29-8cec-f90c994cd6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;components-nav&quot;]/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#components-nav-refund > li > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;components-nav-refund&quot;)/li[1]/a[1][count(. | //*[@href = '/refund' and (text() = 'Refund ' or . = 'Refund ')]) = count(//*[@href = '/refund' and (text() = 'Refund ' or . = 'Refund ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Refund&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e4116ef-835f-4547-8563-cf4185aa8be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/refund</value>
      <webElementGuid>ef86e046-9886-4ab8-bbed-743a2fb9318a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refund </value>
      <webElementGuid>d0803505-bc9e-48a8-9ddc-702a5d647ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;components-nav-refund&quot;)/li[1]/a[1]</value>
      <webElementGuid>1647efe4-45b7-41b8-9062-318680d220d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='components-nav-refund']/li/a</value>
      <webElementGuid>df19c5cf-ae8e-4509-8329-03630d2cdc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund'])[1]/following::a[1]</value>
      <webElementGuid>ba43b00c-6ddb-4821-b3d2-944f1b1dd7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsettled Reconciliation Balance Fluctuations Statistics'])[1]/following::a[2]</value>
      <webElementGuid>6fe12923-20c3-4f68-aead-1a0281af20c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment Refund Request'])[1]/preceding::a[1]</value>
      <webElementGuid>d67d029d-11b2-4439-abdb-13a45612673b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/refund')]</value>
      <webElementGuid>11591ce7-34dd-4091-8952-9198f5ff08c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a</value>
      <webElementGuid>73aacd01-3640-41cc-b554-f2a3f2ae458d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/refund' and (text() = 'Refund ' or . = 'Refund ')]</value>
      <webElementGuid>f3f422f6-7bac-4b80-a248-842af07c93bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
