<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Refund</name>
   <tag></tag>
   <elementGuidId>af49ef15-5c93-4e29-8cec-f90c994cd6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;components-nav-refund&quot;]/li[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;components-nav-refund&quot;)/li[1]/a[1][count(. | //*[@href = '/refund' and (text() = 'Refund ' or . = 'Refund ')]) = count(//*[@href = '/refund' and (text() = 'Refund ' or . = 'Refund ')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#components-nav-refund > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Refund&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>872a3823-fefd-46c9-9cc5-005570b62e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/refund</value>
      <webElementGuid>010dbb62-b57f-43f2-9dd1-d04556b91550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refund </value>
      <webElementGuid>9aff469f-f1e3-4d44-beac-53c13336a66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;components-nav-refund&quot;)/li[1]/a[1]</value>
      <webElementGuid>aeddc319-775b-4442-9d77-70be8503a863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='components-nav-refund']/li/a</value>
      <webElementGuid>703117cc-3792-4157-8760-f1fda9874c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund'])[1]/following::a[1]</value>
      <webElementGuid>eaa0e446-f7e9-4468-a207-33049f455d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsettled Reconciliation Balance Fluctuations Statistics'])[1]/following::a[2]</value>
      <webElementGuid>6af2e615-b0d9-49b8-9916-80a732fca83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment Refund Request'])[1]/preceding::a[1]</value>
      <webElementGuid>91797864-df9b-4704-8cc6-1affc1351424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/refund')]</value>
      <webElementGuid>a54845ff-711f-41b7-95f9-2da2bc0cb304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a</value>
      <webElementGuid>39938709-91a2-4242-8422-b3983f410dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/refund' and (text() = 'Refund ' or . = 'Refund ')]</value>
      <webElementGuid>ea25d119-8c9d-4f40-82fd-996cd4bbcef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
