<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modulerefund</name>
   <tag></tag>
   <elementGuidId>2105a6f4-5bd8-4e39-8bf0-bf2e19a99ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;nav-item-refund&quot;)/a[@class=&quot;nav-link&quot;][count(. | //*[@href = '#' and (text() = 'Refund' or . = 'Refund')]) = count(//*[@href = '#' and (text() = 'Refund' or . = 'Refund')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nav-item-refund&quot;]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-item-refund > a.nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Refund &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b685eedd-58a4-4548-b203-61baa11d9f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3e91987b-b5d3-467c-b062-0e75692053e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#components-nav-refund</value>
      <webElementGuid>870440f6-9c96-486b-bf1e-f132b26ee107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>ca2e9e37-146f-49bb-a0d2-f22ac2a090b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>4678df08-68c2-462c-bc28-2543fa2d968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df0ca573-7b13-4761-8f34-87d05177b331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refund</value>
      <webElementGuid>606ce764-5640-4221-80e1-09f217c2748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-item-refund&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>2a7b33c8-420f-4ba7-8780-a6291911e685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-item-refund']/a</value>
      <webElementGuid>3160b1d4-a92a-4304-b74e-caff67ce4ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsettled Reconciliation Balance Fluctuations Statistics'])[1]/following::a[1]</value>
      <webElementGuid>3922011d-c90a-4563-b9fe-c0cf6949d2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Search'])[1]/following::a[2]</value>
      <webElementGuid>125eea76-0c43-4d1a-b4ee-6bfab0855713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refund'])[2]/preceding::a[1]</value>
      <webElementGuid>af6d8974-625c-44ea-bad9-1202d732d092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>4a3954b4-e039-4269-bda1-be12c5adf094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>d7a8ee9d-a546-4cf5-93b3-0b0a3a197f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Refund' or . = 'Refund')]</value>
      <webElementGuid>6a6099c5-99a4-49f9-9dcb-d84e34b2ee55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
