<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quanlygd</name>
   <tag></tag>
   <elementGuidId>38bcf095-a706-4dc8-a246-a5bd5f89b3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-item-transaction > a.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-item-transaction']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Quản lý giao dịch &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5cdeeee5-9938-4bc7-80a2-a781d3d980f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#components-nav</value>
      <webElementGuid>940587b9-6906-4cb8-89d1-6450dd3f1501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>6ea3b578-3077-4cba-bd07-0927f7b8c9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>152c62e5-e4bf-4c63-b9c1-fcea1304db6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>5479c3b2-4958-4817-80d3-510b8a2ee49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20300cd9-e100-48fe-9e4a-7098782acf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quản lý giao dịch</value>
      <webElementGuid>bd007f6f-8a28-4c61-913c-e267626fbd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-item-transaction&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>109ffa5a-f483-4d01-8db3-8f20b5e7b30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-item-transaction']/a</value>
      <webElementGuid>da584b07-79cc-4183-a555-11cbf1bc6d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm mới hóa đơn'])[1]/following::a[1]</value>
      <webElementGuid>da6405ca-2d50-4326-81a1-2f144deb7c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách hóa đơn'])[1]/following::a[2]</value>
      <webElementGuid>417c9151-ca37-4753-b845-0c42adf1173a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tra cứu giao dịch'])[1]/preceding::a[1]</value>
      <webElementGuid>7c271987-a2be-4213-96c8-9eda5539b3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>c1c6c3b8-d1bf-4dd8-83f0-c4aa81b9797b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>4e75ef40-02e3-4c85-854a-f35ef328f2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Quản lý giao dịch' or . = 'Quản lý giao dịch')]</value>
      <webElementGuid>c98216c7-8021-44fb-9380-930e87e48f34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
