<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quanlygd</name>
   <tag></tag>
   <elementGuidId>38bcf095-a706-4dc8-a246-a5bd5f89b3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nav-item-transaction&quot;]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-item-transaction > a.nav-link</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;nav-item-transaction&quot;)/a[@class=&quot;nav-link&quot;][count(. | //*[@href = '#' and @class = 'nav-link' and (text() = 'Quản lý giao dịch' or . = 'Quản lý giao dịch')]) = count(//*[@href = '#' and @class = 'nav-link' and (text() = 'Quản lý giao dịch' or . = 'Quản lý giao dịch')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Quản lý giao dịch &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db6b4fe9-1521-49b4-80b7-5c2a9674a38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#components-nav</value>
      <webElementGuid>3ee3be16-b3f8-4c97-b2fc-d8f75ce5e118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>64d5ce67-3be9-4b35-b4de-68b08a837144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8f806d95-9f66-42e2-b660-14f29270991f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>90092ea8-999e-46b6-80db-1b2172fec280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be8444bc-0e94-4629-9ff8-bf4ab5df8a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quản lý giao dịch</value>
      <webElementGuid>6772b3f6-1cd3-4d6d-ba9e-fb71c43361f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-item-transaction&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>8d1c5b94-2f84-4ba9-a8e4-e4e6a50c24b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-item-transaction']/a</value>
      <webElementGuid>a1e509a5-75fb-4931-b207-fdfcfeaee0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm mới hóa đơn'])[1]/following::a[1]</value>
      <webElementGuid>fcc8aa99-fada-43ca-8ff9-e51ce695b633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách hóa đơn'])[1]/following::a[2]</value>
      <webElementGuid>a0705f24-9230-44ea-a9f6-00ae860420a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tra cứu giao dịch'])[1]/preceding::a[1]</value>
      <webElementGuid>4ef660c4-44ab-47ea-a4b9-f95c7a6fc483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>26022f77-aa05-448e-a1d6-b40e20c4b3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>447175cb-0793-49e9-a15f-8569c6c37de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Quản lý giao dịch' or . = 'Quản lý giao dịch')]</value>
      <webElementGuid>a4434ac0-a02e-4c40-a988-bd160bcdd964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
